/*********************************************************************************/
/*!
 * \file      system.h
 *
 * \brief     The Same Game v0.1 --> SYSTEM File
 *
 * \details   General fuctions and defines for the whole project.
 *
 * \note      Hardware:    Nintendo 3DS
 * \n         IDE:         DevkitPro 1.6.0
 * \n         Licence:     GNU General Public License V3
 * \n
 * \warning   Copyright:   (C) by DiS-tronics Austria               
 *
 * \author 	  DiS-tronics
 * \date      May 2016
 */
/*********************************************************************************/
#ifndef SYSTEM_H
#define SYSTEM_H

/*-------------------------------------------------------------------------------*/
/*  Include files                                                                */
/*-------------------------------------------------------------------------------*/
#include <3ds.h>
#include <stdio.h>
#include <citro3d.h>
#include <string.h>
#include <stdlib.h>
#include <time.h>

// project related headers
#include "lodepng.h"
#include "samegame.h"
#include "render.h"

// these headers are generated by the build process
#include "vshader_shbin.h"
#include "ballsprites_png.h"

// these headers containing definitions of our image
#include "game_bgr.h"
#include "menu_bgr.h"
#include "options_bgr.h"
#include "won_bgr.h"
#include "over_bgr.h"
#include "again_bgr.h"

/*-------------------------------------------------------------------------------*/
/*  Defines                                                                      */
/*-------------------------------------------------------------------------------*/
#define BUFSIZE         64
#define GAME_PLAY_MODE  1
#define NEW_GAME_MODE   2
#define GAME_END_MODE   3
#define MAIN_MENU_MODE  4
#define OPTIONS_MODE    5
#define POWER_OFF_MODE  6
#define VALID_NEW_TOUCH_POS touch.px > 0 && touch.py > 0 && touch.px != t_queue.px && touch.py != t_queue.py

/*-------------------------------------------------------------------------------*/
/*  Function prototypes                                                          */
/*-------------------------------------------------------------------------------*/
void SYS_TouchDelay(bool *bTouched);
void SYS_WaitForInput(u32 iKey);
bool SYS_UserExit(void);

//---------------------------------------------------------------------------------
#endif // SYSTEM_H